language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
    secure: // TODO
  glob:
    secure: // TODO

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
